name: release
on:
  push:
    tags:
      - v*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
      - name: Release
        run: make release
        env:
          DOCKER_ARGS: -e GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}
